### ISSUE TITLE
[Meta] Polishing

### ISSUE THREAD

**Issue by tobiasdierich** [codelayerhq/likvi-timetracking-desktop#11]
Some design polishing things I'd consider:

- [ ] Remove the clock at the top left
- [ ] Remove the "Idle Seconds" counter (I know it was only there for testing purposes)
- [ ] Give the top container (chart area) a drop shadow, otherwise you might end up with something like this when scrolling (see image [1])
- [ ] The title of the time entries looks too bold
- [ ] Things look out of proportion when using smaller window (see [2])

[1] Notice the bottom border of the chart container: looks like it is broken because of the scrolling position of the time entries

<img width="672" alt="Screenshot 2020-09-23 at 14 12 47" src="https://user-images.githubusercontent.com/20173900/94011154-3e9c0700-fda7-11ea-8976-493965306f70.png">

[2]

<img width="471" alt="Screenshot 2020-09-23 at 14 16 21" src="https://user-images.githubusercontent.com/20173900/94011335-7e62ee80-fda7-11ea-8c4e-b427075c91c0.png">
