### ISSUE TITLE
[meta] Tray Menu

### ISSUE THREAD

**Issue by tobiasdierich** [codelayerhq/likvi-timetracking-desktop#37]
Things we should consider

- [x] Add a "stop current time entry" option which is disabled when no time entry is running
- [ ] Show the current duration of the active time entry below the account email (optional)
- [ ] Add translations (postpone)
